services:
  tagakam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tagakam
    ports:
      - "3004:3000"   # le conteneur écoute maintenant sur 3004
    environment:
      - NODE_ENV=production
      - PORT=3004
      - HOST=0.0.0.0
      - NITRO_PORT=3004
      - NITRO_HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - NUXT_PUBLIC_API_BASE=https://portal.digitalssolutions.de/api
      - API_LOGIN_EMAIL=${API_LOGIN_EMAIL}
      - API_LOGIN_PASSWORD=${API_LOGIN_PASSWORD}
      - API_TENANT_KEY=${API_TENANT_KEY}
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # --- Middlewares ---
      # Force HTTPS dans les requêtes internes
      - "traefik.http.middlewares.tagakam-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

      # Redirection du domaine nu -> www (nom unique pour éviter conflits)
      - "traefik.http.middlewares.tagakam-redirect-to-www.redirectregex.regex=^https?://tagakam\\.de(.*)"
      - "traefik.http.middlewares.tagakam-redirect-to-www.redirectregex.replacement=https://www.tagakam.de$1"
      - "traefik.http.middlewares.tagakam-redirect-to-www.redirectregex.permanent=true"

      # --- Routers ---
      # www.ondiffoline.de -> sert le site
      - "traefik.http.routers.tagakam-www.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam-www.rule=Host(`www.tagakam.de`)"
      - "traefik.http.routers.tagakam-www.tls=true"
      - "traefik.http.routers.tagakam-www.service=tagakam"
      - "traefik.http.routers.tagakam-www.middlewares=tagakam-headers"

      # ondiffoline.de -> redirection vers www
      - "traefik.http.routers.tagakam-root.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam-root.rule=Host(`tagakam.de`)"
      - "traefik.http.routers.tagakam-root.tls=true"
      - "traefik.http.routers.tagakam-root.middlewares=tagakam-redirect-to-www@docker"
      - "traefik.http.routers.tagakam-root.service=noop@internal"

networks:
  traefik-net:
    external: true
