services:
  tagakam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tagakam
    ports:
      - "3004:3004"   # le conteneur écoute maintenant sur 3004
    environment:
      - NODE_ENV=production
      - PORT=3004
      - HOST=0.0.0.0
      - NITRO_PORT=3004
      - NITRO_HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - NUXT_PUBLIC_API_BASE=http://portal.digitalssolutions.de/api
      - NUXT_PORTAL_API_URL=http://portal.digitalssolutions.de/api
      # API Authentication for JWT token (endpoint /config)
      - API_LOGIN_EMAIL=info@tagakam.de
      - API_LOGIN_PASSWORD=tagakam
      # Tenant key for /services, /team, /faq endpoints
      - API_TENANT_KEY=ce9563cab5f81156b3c1f6ba86ace15c5c1c48f97c4a4a68049d7e84f10a4d23
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
    
      # HTTP (Port 80) → Redirect auf HTTPS
      - "traefik.http.routers.tagakam-http.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam-http.rule=Host(`www.tagakam.de`)"
      - "traefik.http.routers.tagakam-http.middlewares=tagakam-https"
      
      - "traefik.http.middlewares.tagakam-https.redirectscheme.scheme=https"
    
      # Redirect tagakam.de → www.tagakam.de
      - "traefik.http.routers.tagakam-root.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam-root.rule=Host(`tagakam.de`)"
      - "traefik.http.routers.tagakam-root.middlewares=tagakam-www-redirect"
      - "traefik.http.routers.tagakam-root.tls=true"
    
      - "traefik.http.middlewares.tagakam-www-redirect.redirectregex.regex=^https?://tagakam\\.de(.*)"
      - "traefik.http.middlewares.tagakam-www-redirect.redirectregex.replacement=https://www.tagakam.de$1"
      - "traefik.http.middlewares.tagakam-www-redirect.redirectregex.permanent=true"
    
      # HTTPS Router
      - "traefik.http.routers.tagakam.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam.rule=Host(`www.tagakam.de`)"
      - "traefik.http.routers.tagakam.tls=true"
      - "traefik.http.routers.tagakam.tls.certresolver=leresolver"

networks:
  traefik-net:
    external: true
