services:
  tagakam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tagakam
    ports:
      - "3004:3004"   # le conteneur Ã©coute maintenant sur 3004
    environment:
      - NODE_ENV=production
      - PORT=3004
      - HOST=0.0.0.0
      - NITRO_PORT=3004
      - NITRO_HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - NUXT_PUBLIC_API_BASE=https://portal.digitalssolutions.de/api
      - API_LOGIN_EMAIL=${API_LOGIN_EMAIL}
      - API_LOGIN_PASSWORD=${API_LOGIN_PASSWORD}
      - API_TENANT_KEY=${API_TENANT_KEY}
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"

      # Service -> port INTERNE (3004)
      - "traefik.http.services.tagakam-xix29f-54.loadbalancer.server.port=3004"

      # --- Middlewares ---
      - "traefik.http.middlewares.tagakam-xix29f-54-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

      # Redirection apex -> www
      - "traefik.http.middlewares.tagakam-xix29f-54-redirect-to-www.redirectregex.regex=^https?://tagakam\\.de(/.*)?$"
      - "traefik.http.middlewares.tagakam-xix29f-54-redirect-to-www.redirectregex.replacement=https://www.tagakam.de$1"
      - "traefik.http.middlewares.tagakam-xix29f-54-redirect-to-www.redirectregex.permanent=true"

      # --- Routers ---
      # www -> sert le site
      - "traefik.http.routers.tagakam-xix29f-54-www.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam-xix29f-54-www.rule=Host(`www.tagakam.de`)"
      - "traefik.http.routers.tagakam-xix29f-54-www.tls=true"
      - "traefik.http.routers.tagakam-xix29f-54-www.service=tagakam-xix29f-54"
      - "traefik.http.routers.tagakam-xix29f-54-www.middlewares=tagakam-xix29f-54-headers"

      # apex -> applique la redirection (vers www)
      - "traefik.http.routers.tagakam-xix29f-54-root.entrypoints=frontendsecure"
      - "traefik.http.routers.tagakam-xix29f-54-root.rule=Host(`tagakam.de`)"
      - "traefik.http.routers.tagakam-xix29f-54-root.tls=true"
      - "traefik.http.routers.tagakam-xix29f-54-root.middlewares=tagakam-xix29f-54-redirect-to-www@docker"
      - "traefik.http.routers.tagakam-xix29f-54-root.service=noop@internal"

networks:
  traefik-net:
    external: true
